config/routes.rb
Rails.application.routes.draw do
  resources :photos
  resources :activity_records
  resources :membership_fees
  resources :membership_types
  mount ActionCable.server => '/cable'

  resources :qr_codes, only:[:new, :create]
  devise_for  :users, controllers: { registrations: :registrations }

  get 'qr_codes/new'

  get 'qr_codes/create'

  get 'activities_attending', to: "activities#activities_attending"
  
  post 'create_activity_record', to: "activity_records#create_activity_record", as: :create_activity_record
  get 'menu', to: "users#menu"


  root "statics#homepage"

  post "activities/:id/book", to:"activities#book", as: :activity_book
  delete 'activities/:id/cancel', to: "activities#cancel", as: :activity_cancel
  
  resources :activities


  resources :users, only: [:index, :show]

  #the do block creates a sub route for messages - the messages route is inside the converstaion block 
  resources :conversations, only: [:index, :create] do
  resources :messages, only: [:index, :create]
  end

  get "home", to: "statics#homepage"
  get "about", to: "statics#about"
  get "contact_us", to:"statics#contact_us"

end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :creator, class_name: "User", foreign_key: "user_id"

  has_and_belongs_to_many :attendees,  class_name: "User", join_table: "activities_users"
  has_many :activity_records

  validates_numericality_of :number_of_places
  mount_uploader :image, ActivityImageUploader

  def places_taken
    attendees.size
  end

  def places_available
    number_of_places - places_taken
  end

end

app/models/activity_record.rb
class ActivityRecord < ApplicationRecord
  belongs_to :activity
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, class_name: "User", foreign_key: "sender_id"
  belongs_to :receiver, class_name: "User", foreign_key: "receiver_id"
  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, scope: :receiver_id
  #scope is like def but used where there is inheriance from ApplicaionRecord
  scope :between, -> (sender_id,receiver_id) do
      where("(conversations.sender_id = ? AND conversations.receiver_id = ?) OR (conversations.receiver_id = ? AND conversations.sender_id = ?)", sender_id, receiver_id, sender_id, receiver_id, )
    end

    def recipient(current_user)
       self.sender_id == current_user.id ? self.receiver : self.sender
    end

    def unread_message_count(current_user)
         self.messages.where("user_id != ? AND read = ?", current_user.id, false).count
    end



end

app/models/converstaion.rb
class Conversation < ApplicationRecord
  belongs_to :sender, class_name: "User", foreign_key: "sender_id"
  belongs_to :receiver, class_name: "User", foreign_key: "receiver_id"
  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, scope: :receiver_id

  scope :between, -> (sender_id,receiver_id) do
      where("(conversations.sender_id = ? AND conversations.receiver_id = ?) OR (conversations.receiver_id = ? AND conversations.sender_id = ?)", sender_id, receiver_id, receiver_id, sender_id)
    end
end

app/models/membership_fee.rb
class MembershipFee < ApplicationRecord
end

app/models/membership_type.rb
class MembershipType < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id


    def time
      created_at.strftime("%d/%m/%y at %l:%M %p")
    end
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :User, class_name: "User", foreign_key: "user_id"

  mount_uploader :image, PhotoImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :created_activities, class_name: "Activity", foreign_key: "user_id"
  has_and_belongs_to_many :activities_attending,-> { distinct }, class_name: "Activity", join_table: "activities_users"
  after_initialize :set_default

  has_many :activity_records, through: :activities

  has_many :photos

  mount_uploader :user_image, UserImageUploader

  def set_default
    self.admin_level ||= 1
    self.total_visits = 0
    self.user_image = '/images/placeholder.png'
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def member_type (current_user)
    case current_user.admin_level
    when 1
      "Member"
    when 2
      "Personal Trainer"
    when 3
      "Admin User"
    when 4
      "Super User"
    end
  end

  def encouragement_icon_total(current_user)
    if current_user.total_visits == 0
      "😡"
    elsif current_user.total_visits > 3
      "🤔"
    elsif current_user.total_visits > 8
      "😊"
    elsif current_user.total_visits > 10
      "😘"
    end
  end

  def encouragement_icon_classes (classes)
    if classes == 0
      "😡"
    elsif classes >3
      "🤔"
    elsif classes > 8
      "😊"
    elsif classes > 10
      "😘"
    end
  end

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  private
    def set_user
      @user = User.find(params[:id])
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/qr_codes_helper.rb
module QrCodesHelper
end

app/helpers/secure_helper.rb
module SecureHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/partials/_back_links.html.erb
<div class="centered_back_link">
  <% if current_user.admin_level > 1%> 
  <%= link_to 'Create New Activity', new_activity_path %>&nbsp|&nbsp
  <% end %>
<%= link_to 'Menu', menu_path %>
</div>

app/views/partials/_nav_bar.html.erb
<header>
  <nav class="navbar navbar-dark bg-primary">
    <div class="container-fluid">
      <button class="navbar-toggler hidden-md-up pull-right" type="button" data-toggle="collapse" data-target="#collapsingNavbar2">
    ☰
      </button>
        <div class="collapse navbar-toggleable-sm" id="collapsingNavbar2">
          <ul class="nav navbar-nav">
          <% if current_user %>
       
          
            <li class="nav-item"><%= link_to"Main Menu", menu_path, class:"admin_nav_link" %></li>

            <li class="nav-item"><%= link_to"All Classes", activities_path, class:"admin_nav_link" %></li>

            <li class="nav-item"><%= link_to"My Classes", activities_attending_path, class:"admin_nav_link" %></li>
            <li class="nav-item"><%= link_to"Membership Card", qr_codes_create_path, class:"admin_nav_link" %></li>
            <li class="nav-item"><%= link_to"Message", conversations_path, class:"admin_nav_link" %></li>
            <li class="nav-item"><%= link_to "Log out", destroy_user_session_path, class:"admin_nav_link", method: :delete %></li>

              <% if current_user.admin_level > 1 %>
              <li class="nav-item"><%= link_to"Memberships", membership_types_path, class:"admin_nav_link" %></li>
              <li class="nav-item"><%= link_to"Fees Paid", membership_fees_path, class:"admin_nav_link" %></li>
              <li class="nav-item"><%= link_to"User List",users_path, class:"admin_nav_link"%></li>
              <% end %>
       
            <% else %>
                <li class="nav-item"><%= link_to "Sign In", new_user_session_path, class:"admin_nav_link" %></li>
                <li class="nav-item"><%= link_to "Register", new_user_registration_path, class:"admin_nav_link" %></li>
            <% end %>
          </div>
        </div>
      </nav>
</header>
<main>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

   
 
 