config/routes.rb
Rails.application.routes.draw do
  resources :photos
  resources :activity_records
  resources :membership_fees
  resources :membership_types
  mount ActionCable.server => '/cable'

  resources :qr_codes, only:[:new, :create]
  devise_for  :users, controllers: { registrations: :registrations }

  get 'qr_codes/new'

  get 'qr_codes/create'

  get 'activities_attending', to: "activities#activities_attending"
  
  post 'create_activity_record', to: "activity_records#create_activity_record", as: :create_activity_record
  get 'menu', to: "users#menu"


  root "statics#homepage"

  post "activities/:id/book", to:"activities#book", as: :activity_book
  delete 'activities/:id/cancel', to: "activities#cancel", as: :activity_cancel
  
  resources :activities


  resources :users, only: [:index, :show]

  #the do block creates a sub route for messages - the messages route is inside the converstaion block 
  resources :conversations, only: [:index, :create] do
  resources :messages, only: [:index, :create]
  end

  get "home", to: "statics#homepage"
  get "about", to: "statics#about"
  get "contact_us", to:"statics#contact_us"

end

app/models/activity_record.rb
class ActivityRecord < ApplicationRecord
  belongs_to :activity
end

app/controllers/activity_records_controller.rb
class ActivityRecordsController < ApplicationController
  before_action :set_activity_record, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /activity_records
  # GET /activity_records.json
  def index
    @activity_records = ActivityRecord.all
  end

  # GET /activity_records/1
  # GET /activity_records/1.json
  def show
  end

  # GET /activity_records/new
  def new
    @activity_record = ActivityRecord.new
  end

  # GET /activity_records/1/edit
  def edit
  end

  # POST /activity_records
  # POST /activity_records.json
  def create
    @activity_record = ActivityRecord.new(activity_record_params)

    respond_to do |format|
      if @activity_record.save
        format.html { redirect_to @activity_record, notice: 'Activity record was successfully created.' }
        format.json { render :show, status: :created, location: @activity_record }
      else
        format.html { render :new }
        format.json { render json: @activity_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activity_records/1
  # PATCH/PUT /activity_records/1.json
  def update
    respond_to do |format|
      if @activity_record.update(activity_record_params)
        format.html { redirect_to @activity_record, notice: 'Activity record was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity_record }
      else
        format.html { render :edit }
        format.json { render json: @activity_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activity_records/1
  # DELETE /activity_records/1.json
  def destroy
    @activity_record.destroy
    respond_to do |format|
      format.html { redirect_to activity_records_url, notice: 'Activity record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity_record
      @activity_record = ActivityRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_record_params
      params.require(:activity_record).permit(:activity_id, :type, :date, :status, :user_id)
    end
end

app/helpers/activity_records_helper.rb
module ActivityRecordsHelper
end

app/views/activity_records/_form.html.erb
<%= form_for(activity_record) do |f| %>
  <% if activity_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activity_record.errors.count, "error") %> prohibited this activity_record from being saved:</h2>

      <ul>
      <% activity_record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :activity_id %>
    <%= f.number_field :activity_id %>
  </div>

  <div class="field">
    <%= f.label :type %>
    <%= f.text_field :type %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.text_field :date %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activity_records/edit.html.erb
<h1>Editing Activity Record</h1>

<%= render 'form', activity_record: @activity_record %>

<%= link_to 'Show', @activity_record %> |
<%= link_to 'Back', activity_records_path %>

app/views/activity_records/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Activity Records</h1>

<table>
  <thead>
    <tr>
      <th>Activity</th>
      <th>Type</th>
      <th>Date</th>
      <th>Status</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activity_records.each do |activity_record| %>
      <tr>
        <td><%= activity_record.activity_id %></td>
        <td><%= activity_record.type %></td>
        <td><%= activity_record.date %></td>
        <td><%= activity_record.status %></td>
        <td><%= activity_record.user_id %></td>
        <td><%= link_to 'Show', activity_record %></td>
        <td><%= link_to 'Edit', edit_activity_record_path(activity_record) %></td>
        <td><%= link_to 'Destroy', activity_record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity Record', new_activity_record_path %>

app/views/activity_records/new.html.erb
<h1>New Activity Record</h1>

<%= render 'form', activity_record: @activity_record %>

<%= link_to 'Back', activity_records_path %>

app/views/activity_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Activity:</strong>
  <%= @activity_record.activity_id %>
</p>

<p>
  <strong>Type:</strong>
  <%= @activity_record.type %>
</p>

<p>
  <strong>Date:</strong>
  <%= @activity_record.date %>
</p>

<p>
  <strong>Status:</strong>
  <%= @activity_record.status %>
</p>

<p>
  <strong>User:</strong>
  <%= @activity_record.user_id %>
</p>

<%= link_to 'Edit', edit_activity_record_path(@activity_record) %> |
<%= link_to 'Back', activity_records_path %>