config/routes.rb
Rails.application.routes.draw do
  resources :photos
  resources :activity_records
  resources :membership_fees
  resources :membership_types
  mount ActionCable.server => '/cable'

  resources :qr_codes, only:[:new, :create]
  devise_for  :users, controllers: { registrations: :registrations }

  get 'qr_codes/new'

  get 'qr_codes/create'

  get 'activities_attending', to: "activities#activities_attending"
  
  post 'create_activity_record', to: "activity_records#create_activity_record", as: :create_activity_record
  get 'menu', to: "users#menu"


  root "statics#homepage"

  post "activities/:id/book", to:"activities#book", as: :activity_book
  delete 'activities/:id/cancel', to: "activities#cancel", as: :activity_cancel
  
  resources :activities


  resources :users, only: [:index, :show]

  #the do block creates a sub route for messages - the messages route is inside the converstaion block 
  resources :conversations, only: [:index, :create] do
  resources :messages, only: [:index, :create]
  end

  get "home", to: "statics#homepage"
  get "about", to: "statics#about"
  get "contact_us", to:"statics#contact_us"

end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :creator, class_name: "User", foreign_key: "user_id"

  has_and_belongs_to_many :attendees,  class_name: "User", join_table: "activities_users"
  has_many :activity_records

  validates_numericality_of :number_of_places
  mount_uploader :image, ActivityImageUploader

  def places_taken
    attendees.size
  end

  def places_available
    number_of_places - places_taken
  end

end

app/models/activity_record.rb
class ActivityRecord < ApplicationRecord
  belongs_to :activity
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, class_name: "User", foreign_key: "sender_id"
  belongs_to :receiver, class_name: "User", foreign_key: "receiver_id"
  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, scope: :receiver_id
  #scope is like def but used where there is inheriance from ApplicaionRecord
  scope :between, -> (sender_id,receiver_id) do
      where("(conversations.sender_id = ? AND conversations.receiver_id = ?) OR (conversations.receiver_id = ? AND conversations.sender_id = ?)", sender_id, receiver_id, sender_id, receiver_id, )
    end

    def recipient(current_user)
       self.sender_id == current_user.id ? self.receiver : self.sender
    end

    def unread_message_count(current_user)
         self.messages.where("user_id != ? AND read = ?", current_user.id, false).count
    end



end

app/models/converstaion.rb
class Conversation < ApplicationRecord
  belongs_to :sender, class_name: "User", foreign_key: "sender_id"
  belongs_to :receiver, class_name: "User", foreign_key: "receiver_id"
  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, scope: :receiver_id

  scope :between, -> (sender_id,receiver_id) do
      where("(conversations.sender_id = ? AND conversations.receiver_id = ?) OR (conversations.receiver_id = ? AND conversations.sender_id = ?)", sender_id, receiver_id, receiver_id, sender_id)
    end
end

app/models/membership_fee.rb
class MembershipFee < ApplicationRecord
end

app/models/membership_type.rb
class MembershipType < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id


    def time
      created_at.strftime("%d/%m/%y at %l:%M %p")
    end
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :User, class_name: "User", foreign_key: "user_id"

  mount_uploader :image, PhotoImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :created_activities, class_name: "Activity", foreign_key: "user_id"
  has_and_belongs_to_many :activities_attending,-> { distinct }, class_name: "Activity", join_table: "activities_users"
  after_initialize :set_default

  has_many :activity_records, through: :activities

  has_many :photos

  mount_uploader :user_image, UserImageUploader

  def set_default
    self.admin_level ||= 1
    self.total_visits = 0
    self.user_image = '/images/placeholder.png'
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def member_type (current_user)
    case current_user.admin_level
    when 1
      "Member"
    when 2
      "Personal Trainer"
    when 3
      "Admin User"
    when 4
      "Super User"
    end
  end

  def encouragement_icon_total(current_user)
    if current_user.total_visits == 0
      "😡"
    elsif current_user.total_visits > 3
      "🤔"
    elsif current_user.total_visits > 8
      "😊"
    elsif current_user.total_visits > 10
      "😘"
    end
  end

  def encouragement_icon_classes (classes)
    if classes == 0
      "😡"
    elsif classes >3
      "🤔"
    elsif classes > 8
      "😊"
    elsif classes > 10
      "😘"
    end
  end

  
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
    @users = User.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = current_user.photos.new(photo_params)
    respond_to do |format|
      if @photo.save
        format.html { redirect_to photos_path, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:title, :description, :status, :album, :poster, :image)
    end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def homepage
  end

  def about
  end

  def contact_us
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  private
    def set_user
      @user = User.find(params[:id])
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/qr_codes_helper.rb
module QrCodesHelper
end

app/helpers/secure_helper.rb
module SecureHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/statics/_nav_bar.html.erb
<header>
 <nav class="navbar navbar-light bg-faded">
    <ul class="nav navbar-nav">
     <% if current_user %>
      <li class="nav-item">Current User...<%= current_user.email %>&nbspUser Id...<%=current_user.id%></li>
      <li class="nav-item"><%= link_to"All Classes", activities_path %></li>
      <li class="nav-item"><%= link_to"My Classes", activities_attending_path %></li>
      <li class="nav-item"><%= link_to"Membership Card", qr_codes_create_path %></li>
      <li class="nav-item"><%= link_to"Message", conversations_path %></li>
      <li class="nav-item"><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>

        <% if current_user.admin_level > 2 %>
          <li class="nav-item"><%= link_to"Memberships", membership_types_path %></li>
          <li class="nav-item"><%= link_to"Fees Paid", membership_fees_path %></li>
          <li class="nav-item"><%= link_to"User List",users_path%></li>
        <% end %>
      
      <% else %>
      <li class="nav-item"><%= link_to "Sign In", new_user_session_path %></li>
      <li class="nav-item"><%= link_to "Register", new_user_registration_path %></li>
      <% end %>

    </ul>
  </nav>
</header>
<main>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

app/views/statics/about.html.erb
<body class="home">
  <div class="shader">
    <div class="home_container">
      <h2 class="home_h2">About the My Gym App</h2>
      <div>
        <blockquote>The my Gym app is designed to enable owners trainers and members get the most out of the gym it has features to help with administration, communication, organisation and motivation.... </blockquote>
        <ul>
          <li class="homepage_nav">Administration...The my gym app enables new members to register on line, the system has a full password secure administraion suite built in and incoprorates QR code technology to generate a membership card which could be linked to a door entry system or turnstile. The membership card will in a future release be linked to membership fee payment records. Owners can see who has and who has not paid and can maintain a list of different membership types.</li>
          <li class="homepage_nav">Trainers can add edit and update classes they provide and see statistics on how many users have attended classes.</li>
          <li class="homepage_nav">There is a secure messaging system which means trainers and members do not have to use their personal email, messages or mobile number for communication</li>
          <li class="homepage_nav">The sytem can provide motivation through simple statistics on user visits, this could be liked to motivational reminder messages in future</li>
        </ul>
      </div>
      <ul>
        <li><%=link_to"Home",home_path, class: "homepage_nav"%></li>
        <li class="homepage_nav">Gallery</li>
        <li><%=link_to"Contact Us",contact_us_path ,class: "homepage_nav"%></li>
      </ul>
    </div>
  </div>
</body>

app/views/statics/contact_us.html.erb
<body class="home">
  <div class="shader">
    <div class="home_container">
      <h2 class="home_h2">About the My Gym App</h2>
      <div>
        <ul>
          <li class="homepage_nav">Created By Jules Jam GA WDI 21</li>
          <li class="homepage_nav">Telephone: 07805 574707</li>
          <li class="homepage_nav">Email:<a href="mailto:julian.wyatt@1xdconsulting.co.uk?Subject=WDI-21 mygym app" target="_top">Send Mail</a></li>
          <li class="homepage_nav">On paper: 6 Sibella Rd, London SW4 6HX</li>
        </ul>
      </div>
      <ul>
        <li><%=link_to"Home",home_path, class: "homepage_nav"%></li>
        <li class="homepage_nav">Gallery</li>
        <li><%=link_to"Contact Us",contact_us_path ,class: "homepage_nav"%></li>
      </ul>
    </div>
  </div>
</body>

app/views/statics/homepage.html.erb
<body class="home">
  <div class="shader">
    <div class="home_container">
      <h1 class="home_h1"> My Gym </h1>
      <h2 class="home_h2">Welcome to the Gym<br><br>Opening times</h2>

      <div id="opening_times">
        <ul>
          <li class="homepage_nav">Monday: 7:00am to 10:00pm</li>
          <li class="homepage_nav">Tuesday: 7:00am to 10:00pm</li>
          <li class="homepage_nav">Wednesday: 7:00am to 10:00pm</li>
          <li class="homepage_nav">Thursday: 7:00am to 10:00pm</li>
          <li class="homepage_nav">Friday: 7:00am to 9:00pm</li>
          <li class="homepage_nav">Saturday: 8:00am to 3:00pm</li>
          <li class="homepage_nav">Sunday Closed</li>

        </ul>
      </div>
      <div >
        <%= link_to"SIGN IN", new_user_session_path, class: "button lrg_button"%>
      </div>
      <div class="welcome_bottom_nav">
        <ul>
          <li><%=link_to"More Info...",about_path, class: "homepage_nav"%></li>
          <li class="homepage_nav">Gallery</li>
          <li><%=link_to"Contact Us",contact_us_path ,class: "homepage_nav"%></li>
        </ul>
      </div>
    </div>
  </div>
</body>