config/routes.rb
Rails.application.routes.draw do
  resources :photos
  resources :activity_records
  resources :membership_fees
  resources :membership_types
  mount ActionCable.server => '/cable'

  resources :qr_codes, only:[:new, :create]
  devise_for  :users, controllers: { registrations: :registrations }

  get 'qr_codes/new'

  get 'qr_codes/create'

  get 'activities_attending', to: "activities#activities_attending"
  
  post 'create_activity_record', to: "activity_records#create_activity_record", as: :create_activity_record
  get 'menu', to: "users#menu"


  root "statics#homepage"

  post "activities/:id/book", to:"activities#book", as: :activity_book
  delete 'activities/:id/cancel', to: "activities#cancel", as: :activity_cancel
  
  resources :activities


  resources :users, only: [:index, :show]

  #the do block creates a sub route for messages - the messages route is inside the converstaion block 
  resources :conversations, only: [:index, :create] do
  resources :messages, only: [:index, :create]
  end

  get "home", to: "statics#homepage"
  get "about", to: "statics#about"
  get "contact_us", to:"statics#contact_us"

end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :creator, class_name: "User", foreign_key: "user_id"

  has_and_belongs_to_many :attendees,  class_name: "User", join_table: "activities_users"
  has_many :activity_records

  validates_numericality_of :number_of_places
  mount_uploader :image, ActivityImageUploader

  def places_taken
    attendees.size
  end

  def places_available
    number_of_places - places_taken
  end

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all

 
    
  end

  def activities_attending
    @activities_attending = current_user.activities_attending
    @user=User.all
  
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
    if current_user.admin_level<3
      flash[:notice] = 'You do not have the authority to amend this activity.'
      redirect_to activities_path
    end
  end

  # POST /activities
  # POST /activities.json
  def create

    @activity = Activity.new(activity_params)
    @activity.creator = current_user

    respond_to do |format|
      if @activity.save
        format.html { redirect_to menu_path, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def cancel
    activity = Activity.find(params[:id])
    current_user.activities_attending.delete(activity) if activity
    flash[:notice] = 'Event was cancelled.'
    redirect_to activities_attending_path
  end

  def book
    activity = Activity.find(params[:id])
    current_user.activities_attending << activity
    flash[:notice] = 'Event was saved.'
    redirect_to activities_attending_path
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:activity_name, :description, :location, :date, :start_time, :duration, :number_of_places, :status, :active, :image, :places_taken)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= form_for(activity) do |f| %>
  <% if activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :activity_name %><br>
    <%= f.text_field :activity_name %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :location %><br>
    <%=  f.select :location, [["Gym Floor","Gym Floor"], ["Studio 1","Studio 1"], ["Yoga Studio","Yoga Studio"],["Spin Room","Spin Room"],["Pool","Pool"]] %>
  </div>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>

  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.time_select :start_time%>
  </div>

  <div class="field">
    <%= f.label :duration %><br>
    <%= f.time_select :duration, :default => {:hour => '00', :minute => '50'}%>
  </div>

  <div class="field">
    <%= f.label :number_of_places %><br>
    <%= f.number_field :number_of_places %>
  </div>

  <div class="field">
    <%= f.label :status %><br>
    <%= f.select :status, [["Open For Booking","Open For Booking"], ["Full","Full"], ["Cancelled","Cancelled"],["Attended","Attended"]] %>
    
  </div>

  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active, :checked => true %>
  </div>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>

 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activities/activities_attending.html.erb
<p id="notice"><%= notice %></p>

<h1 class="title">Your Activities</h1>


<div class="centered_back_link">
  <%= link_to 'Back', menu_path %>&nbsp|&nbsp
  <%= link_to 'Choose a new activity', activities_path %>
</div>
<% @activities_attending.each do |activity| %>
  <div class="card card-outline-primary text-xs-center">
    <div class="card-block">
      <div class="card-user-thumb">
        <%= image_tag activity.image %> 
      </div>
       <h4> <%= activity.activity_name %></h4>
       <h5><%= activity.location %></h5>
       <p> <%= activity.description %></p>
          <blockquote class="card-blockquote">
            Date: <%= activity.date %> &nbspStart Time: <%activity.start_time.strftime("%H:%M:%S") %>&nbspDuration:<%= activity.duration.strftime("%H:%M:%S") %>&nbspAvailable Places: <% places_available = activity.number_of_places.to_i - activity.places_taken.to_i%><%= places_available%> This activity is being run by <%=activity.creator.first_name%>
          </blockquote>
          <div class="card_bottom_nav">
          
          <%= link_to 'View / Cancel this activity', activity %><br>
          
          </div>
        </div>
      </div>
<% end %>

app/views/activities/edit.html.erb
<div class="show_card">
  <h1>Amend Activity Details</h1>

  <%= render 'form', activity: @activity %>

  <%= link_to 'Show', @activity %> |
  <%= link_to 'Back', activities_path %>
</div>

app/views/activities/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="title">Available Activities</h1>

<%= render "partials/back_links"%>



<% @activities.each do |activity| %>
  <% if activity.active %>
   <div class="card card-outline-primary text-xs-center">
     <div class="card-block">
       <div class="card-user-thumb">
         <%= image_tag activity.image, width: 200 %> 
       </div>
        <h4> <%= activity.activity_name %></h4>
        <h5><%= activity.location %></h5>
        <p> <%= activity.description %></p>
          <blockquote class="card-blockquote">
               Date: <%= activity.date %> &nbspStart Time: <%= activity.start_time.strftime("%H:%M:%S") %>&nbspDuration:<%= activity.duration.strftime("%H:%M:%S") %> Places Available: <%= activity.places_available%>&nbspThis activity is being run by: <%=activity.creator.first_name%><br><%= activity.status %>
          </blockquote>

        <% if current_user.admin_level >1 %>
          <ul>
            <div class=attendee_list></div>
            <% activity.attendees.each do |user| %>
              <li><%= user.full_name %>
            <% end %>
          </ul>        
        <%end%>

        <div class="card_bottom_nav">
          <%= link_to 'View', activity %>
          <% if current_user.admin_level > 1%>
          &nbsp|&nbsp
          <%= link_to 'Edit', edit_activity_path(activity) %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/activities/new.html.erb
<div class="show_card">
<h1>Create a New Activity</h1>

  <%= render 'form', activity: @activity %>

  <%= link_to 'Back', activities_path %>
</div>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>
<div class="show_card">
  <p>
    <strong>Activity name:</strong>
    <%= @activity.activity_name %>
  </p>
  <% if current_user.admin_level <2 %>
    <p>
      
      <%=image_tag @activity.image %>
    </p>
  <% end %>
  
  
  <p>
    <strong>Description:</strong>
    <%= @activity.description %>
  </p>
  
  <p>
    <strong>Location:</strong>
    
    <%= @activity.location %>
  </p>
  
  <p>
    <strong>Date:</strong>
    <%= @activity.date %>
  </p>
  
  <p>
    <strong>Start time:</strong>
    <%= @activity.start_time.strftime("%H:%M:%S")%>
  </p>
  
  <p>
    <strong>Duration:</strong>
    <%= @activity.duration.strftime("%H:%M:%S") %>
  </p>
  
  <p>
    <strong>Number of places:</strong>
    <%= @activity.number_of_places %>
  </p>
  
  <p>
    <strong>Status:</strong>
    <%= @activity.status %>
  </p>
  
  <p>
    <strong>Active:</strong>
    <%= @activity.active %>
  </p>
  
  
  <p>
    <strong>Places taken:</strong>
    <%= @activity.places_available %>
  </p>
  
  <p>
    <strong>Created By</strong>
    <%= @activity.creator.first_name%>
  </p>
</div>
  <% if current_user.admin_level >1 %>
    <ul>
        <div class="show_page_sub_header">Attendees</div>
      <% @activity.attendees.each do |user| %>
        <li><%= user.full_name %>
      <% end %>
    </ul>        
  <%end%>
  

<div class="centered_back_link">
  <div class="button_show">
  <% if @activity.places_available > 0 && current_user.admin_level <2 %>
    <%= link_to activity_book_path, method: :post do %>
    Book <%= @activity.activity_name %>&nbsp<%= @activity.date %>&nbsp<%= @activity.start_time %><br>
    <% end%>
  <% else %>
    <%if current_user.admin_level < 2%>
      FULLY BOOKED
    <% end %>
  <% end %>
  </div>
    <%= link_to 'Cancel This Activity', activity_cancel_path, method: :delete, data: { confirm: 'Are you sure?' } %>
   <% if current_user.admin_level >1 %>
  &nbsp | &nbsp
   <%= link_to 'Edit', edit_activity_path(@activity) %> 
 <% end %>|
  <%= link_to 'Back', activities_path %>
</div>